### ISSUE TITLE
What is the difference from ShiftDDPM

### ISSUE THREAD

**Issue by GoldenBechelor** [YangLing0818/ContextDiff#2]
Nice work! But I want to know what is the difference between the formula used and derivated in your paper and that in [ShiftDDPM](https://arxiv.org/abs/2302.02373)? Is it just a special case of ShiftDDPM?

**Comment by YangLing0818** [comment]
> Nice work! But I want to know what is the difference between the formula used and derivated in your paper and that in [ShiftDDPM](https://arxiv.org/abs/2302.02373)? Is it just a special case of ShiftDDPM?

Thanks for your interest! Our work integrates the cross-modal information that considers the interactions between text and visual content into the diffusion process, while ShiftDDPM only incorporates textual information. Thus our integration is of a higher order, and this is also our critical difference compared to ShiftDDPM.
